name: Deploy Blog
on: [push] # 当有新push时运行
env:
  TZ: Asia/Shanghai
jobs:
  build: # 一项叫做build的任务
    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkou
      - name: install rust
        run: sudo apt install cargo
      - name: publish
        run: |
          # publish
          cargo login $CARGO_REGISTRY_TOKEN
          cargo package
          cargo publish

